Add new data upload element
mapbender/mapbender pull request #1560
Opened 2024-04-04 14:03 UTC by PhilVanB

Added new data upload element for GeoJSON, KML, GML and GPX upload.

2024-04-05 11:03 UTC, astroidex commented
- text drop file: small
- icon smaller
- border 2px and mapbender gray 

.mb-element-dataupload .dropFileArea {
  border: 2px dashed gray;

2024-04-05 11:05 UTC, astroidex commented
KML is visualized like that. Is that ok?

![Bildschirmfoto vom 2024-04-05 12-59-57](https://github.com/mapbender/mapbender/assets/996298/a2d65a73-3ffa-4c9c-95b2-960cd141717f)
![Bildschirmfoto vom 2024-04-05 12-59-21](https://github.com/mapbender/mapbender/assets/996298/c45199d5-6fa1-4037-9574-853fa00c9a9a)

2024-04-05 11:29 UTC, astroidex commented
Although the help text was changed it is not visible in the application

![Bildschirmfoto vom 2024-04-05 13-29-02](https://github.com/mapbender/mapbender/assets/996298/2bdf972f-1723-48ed-8885-97a726b9e6e2)
![Bildschirmfoto vom 2024-04-05 13-29-02](https://github.com/mapbender/mapbender/assets/996298/7e130372-1384-432e-b26b-8c7519f184e0)

2024-04-05 11:34 UTC, astroidex requested changes

2024-04-05 11:34 UTC, astroidex commented on src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
> +            fileupload: 'Or choose your files'
or small o

2024-04-05 11:34 UTC, astroidex commented on src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
> +            gml: 'GML format could not be identified!'
! or .

2024-04-05 11:34 UTC, astroidex commented on src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
> +            helpText: 'Here you can upload files in GeoJSON, KML, GML and GPX format.'
You can upload ... without Here

2024-04-05 11:34 UTC, astroidex commented on src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
> +        helpText: 'Hier können Sie Dateien im Format GeoJSON, KML, GML und GPX hochladen.'
Maybe better
helpText: 'Es können Dateien im Format GeoJSON, KML, GML und GPX hochgeladen werden.'

2024-04-05 11:34 UTC, astroidex commented on src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
> +        description: 'Datei Import für GeoJSON, KML, GML, GPX'
description: 'Laden von Dateien im den Formaten GeoJSON, KML, GML und GPX.'

2024-04-05 11:37 UTC, astroidex commented
Please change color of the heading row in the table (name) to white to correspond with the other elements (see search router / sketch / view manager / print queue
![Bildschirmfoto vom 2024-04-05 13-35-43](https://github.com/mapbender/mapbender/assets/996298/05903c01-5f1e-4edb-943f-4a997c7ecf81)

2024-04-05 11:40 UTC, astroidex commented
- when you have to scroll some parts are not visible
- please make the dashed bubble a bit smaller

![dataupload_scroll](https://github.com/mapbender/mapbender/assets/996298/bb94579b-046e-4dc4-9b5a-d292d1701d18)

2024-04-11 06:46 UTC, astroidex commented on src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
> +            title: 'Upload Data'
fixed

2024-04-11 07:00 UTC, astroidex commented
![Bildschirmfoto vom 2024-04-11 08-58-30](https://github.com/mapbender/mapbender/assets/996298/62c16431-efd2-4640-a5bd-d3cf70a51a01)

- Name is not shown completely at the bottom -> see p g..

2024-04-11 07:02 UTC, astroidex requested changes

2024-04-11 13:22 UTC, astroidex approved these changes

2024-04-15 15:22 UTC, Phocacius commented on src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
> +        helpInfo: 'Der Standardwert <code>mb.core.dataupload.admin.helpText</code> bedeutet "Hier können Sie Dateien im Format GeoJSON, KML, GML und GPX hochladen." in der Sprache des Nutzers'
Ist schon richtig wie es hier steht: Der Standardwert ist `mb.core.dataupload.admin.helpText`, und da ist nicht direkt offensichtlich wofür der steht, und das ist im Helptext erklärt.

2024-04-15 15:57 UTC, Phocacius approved these changes

2024-04-15 15:57 UTC, merged