filter layouts; colour highlighting of search results
mapbender/mapbender pull request #1632
Opened 2024-09-12 06:53 UTC by dholler1011

Add filter to backend layouts; colour highlighting of search results in backend layouts and backend layersets

2024-09-20 05:48 UTC, astroidex commented
- works fine
- let's discuss the color in the Mapbender team. Maybe .bg-info-subtle would fit better
- https://getbootstrap.com/docs/5.3/utilities/background/

2024-09-23 12:16 UTC, Phocacius requested changes
All in all good job, I have two minor remarks.

2024-10-01 10:19 UTC, dholler1011 commented on src/Mapbender/ManagerBundle/Resources/views/Application/form-elements.html.twig
> +<div class="row">
Sorry, I don't know what you exactly mean. Can you please explain this in more detail?

2024-10-01 11:25 UTC, Phocacius commented on src/Mapbender/ManagerBundle/Resources/views/Application/form-elements.html.twig
> +<div class="row">
Sorry for being unclear here. In the layout box with the filter there is a significant margin at the top of the box. When comparing to the layerset filter you can see it clearly:

Layout:

![grafik](https://github.com/user-attachments/assets/36bb6657-d361-492c-8fdb-00f616ed9106)

Layerset:

![grafik](https://github.com/user-attachments/assets/f092c305-7dce-418c-b259-e0b7cbb9ca42)

2024-10-17 11:50 UTC, astroidex commented
- I tested the feature. It looks good.

Still some fixes nedded

1. avoid filter for WMS or WMTS in list of WMS-Instances
- because it will highlight all services
- if it is too much effort we can ignore it
![photo_2024-10-17_13-46-48](https://github.com/user-attachments/assets/f4cd107d-fc5e-45d3-90cb-bfef17ef0443)


2. Filter in Sources / Shared instance list -  Allow to search for the Title and WMS number
- at the moment you can not search for a word in the title of the WMS or for the number of the WMS
- this should be possible

2024-10-17 12:11 UTC, Phocacius commented
My previous comments are fixed, thank you! Code looks all good now,

I have one additional remark to Astrids comments: Searching for the placeholder dummy text should also not be possible:

![grafik](https://github.com/user-attachments/assets/d9421f83-7a67-484c-9a86-f8653890e1c2)

2024-10-18 13:49 UTC, Phocacius approved these changes

2024-10-18 13:50 UTC, merged